#!/usr/bin/env python3
# Copyright © The Daybrite Project
# SPDX-License-Identifier: MPL-2.0
#
# conformance-claims.py <conformance.json> [--matrix docs/coverage-matrix.md] [--out verified.md]
#
# Holds a conformance run against what Day declares (docs/testing.md). Two things come out:
#
#   1. Claims. Every leg's `conformance.json` records what its toolkit answered for each `Cap` during
#      the run. docs/coverage-matrix.md is generated from source and says what each backend
#      answers; a leg whose answer differs means the published matrix is wrong for that target,
#      and this exits 1 naming each disagreement. A `?` cell (decided at run time) accepts any
#      answer and reports the one it got.
#   2. The verified matrix: per built-in kind and target, whether every case that proves the
#      kind passed there (`✓`), any failed (`✗`), or all were skipped (`·`), written to --out
#      for the results artifact (and, later, the website's coverage page).
#
# The input is the merged object the `conformance (results)` job writes: each leg's
# conformance.json keyed by the path it was written at, `<target>[/<device>]/<variant>`.

import json
import re
import sys

# The coverage matrix's backend column for each target.
COLUMN = {
    "macos-appkit": "appkit",
    "ios-uikit": "uikit",
    "linux-gtk": "gtk",
    "macos-gtk": "gtk",
    "windows-gtk": "gtk",
    "linux-qt": "qt",
    "macos-qt": "qt",
    "windows-qt": "qt",
    "windows-winui": "xaml",
    "windows-xaml": "xaml",
    "android-mdc": "android",
    "harmony-arkui": "arkui",
    "web-dom": "dom",
}


def declared_caps(matrix_path):
    """`{cap: {column: cell}}` from the Capabilities table of the coverage matrix."""
    text = open(matrix_path, encoding="utf-8").read()
    section = text.split("## Capabilities", 1)[1]
    rows = [l for l in section.splitlines() if l.startswith("|")]
    header = [c.strip() for c in rows[0].strip("|").split("|")]
    out = {}
    for row in rows[2:]:
        cells = [c.strip() for c in row.strip("|").split("|")]
        m = re.fullmatch(r"`(\w+)`", cells[0])
        if m:
            out[m.group(1)] = dict(zip(header[1:], cells[1:]))
    return out


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__)
        return 2
    results_path = args[0]
    matrix_path = "docs/coverage-matrix.md"
    out_path = None
    if "--matrix" in args:
        matrix_path = args[args.index("--matrix") + 1]
    if "--out" in args:
        out_path = args[args.index("--out") + 1]

    results = json.load(open(results_path, encoding="utf-8"))
    declared = declared_caps(matrix_path)
    # The matrix spells "unsupported" as an en dash; the results as a hyphen.
    normalize = {"N": "N", "E": "E", "–": "-", "-": "-"}

    problems, notes = [], []
    verified = {}  # kind -> target -> mark
    for leg, record in sorted(results.items()):
        target = record.get("target") or leg.split("/")[0]
        column = COLUMN.get(target)
        caps = record.get("caps") or {}
        if column and caps:
            for cap, answer in sorted(caps.items()):
                cell = declared.get(cap, {}).get(column)
                if cell is None:
                    problems.append(f"{leg}: {cap} answered {answer}, but the matrix has no row for it")
                elif cell == "?":
                    notes.append(f"{leg}: {cap} decided at run time: {answer}")
                elif normalize.get(cell) != answer:
                    problems.append(f"{leg}: {cap} answered {answer}, the matrix declares {cell}")
        elif column and not caps:
            notes.append(f"{leg}: no capability answers recorded (an older CLI or app)")
        for test in (record.get("tests") or {}).values():
            for key in test.get("proves") or []:
                if not key.startswith("kind:"):
                    continue
                kind = key[len("kind:"):]
                cell = verified.setdefault(kind, {})
                previous = cell.get(target)
                verdict = test.get("verdict")
                mark = {"pass": "✓", "skip": "·"}.get(verdict, "✗")
                # One failure anywhere marks the cell; a pass beats a skip.
                if previous == "✗" or (previous == "✓" and mark == "·"):
                    continue
                cell[target] = mark

    for note in notes:
        print(f"note: {note}")
    for problem in problems:
        print(f"MISMATCH: {problem}")

    if out_path:
        targets = sorted({t for cells in verified.values() for t in cells})
        lines = [
            "# Verified matrix",
            "",
            "What the conformance run proved, per built-in kind and target: `✓` every case that",
            "proves the kind passed there, `✗` one failed, `·` all were skipped. Generated by",
            "scripts/ci/conformance-claims.py from this run's results.",
            "",
            "| kind | " + " | ".join(targets) + " |",
            "|---|" + "---|" * len(targets),
        ]
        for kind in sorted(verified):
            row = verified[kind]
            lines.append(f"| `{kind}` | " + " | ".join(row.get(t, " ") for t in targets) + " |")
        open(out_path, "w", encoding="utf-8").write("\n".join(lines) + "\n")

    print(
        f"conformance claims: {len(results)} leg(s), {len(problems)} mismatch(es), "
        f"{len(verified)} kind(s) in the verified matrix"
    )
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
