#!/usr/bin/env bash
# Regenerate docs/duty-matrix.md — the Toolkit-duty conformance table (which backend implements
# which trait method vs inheriting the day-spec default). CI runs this and fails on drift
# (`git diff --exit-code docs/duty-matrix.md`), so the table can never rot: adding a duty or an
# implementation without regenerating the matrix is a red build.
#
#     scripts/ci/duty-matrix.sh
set -euo pipefail
cd "$(dirname "$0")/../.."

python3 - <<'EOF'
import re
from pathlib import Path

spec = Path("crates/day-spec/src/lib.rs").read_text()
m = re.search(r"pub trait Toolkit[^\n]*\{(.*?)\n\}", spec, re.S)
assert m, "trait Toolkit not found in day-spec"
body = m.group(1)

# A duty is `fn name(...)`; it is REQUIRED when its declaration hits `;` before any `{` body.
duties = []
for dm in re.finditer(r"\n    fn (\w+)", body):
    name = dm.group(1)
    rest = body[dm.end() :]
    semi = rest.find(";")
    brace = rest.find("{")
    required = semi != -1 and (brace == -1 or semi < brace)
    duties.append((name, required))

backends = [
    ("appkit", "toolkits/day-appkit/src/lib.rs"),
    ("uikit", "toolkits/day-uikit/src/lib.rs"),
    ("gtk", "toolkits/day-gtk/src/lib.rs"),
    ("qt", "toolkits/day-qt/src/lib.rs"),
    ("winui", "toolkits/day-winui/src/lib.rs"),
    ("android", "toolkits/day-android/src/lib.rs"),
    ("arkui", "toolkits/day-arkui/src/lib.rs"),
    ("mock", "crates/day-mock/src/lib.rs"),
]
sources = {name: Path(path).read_text() for name, path in backends}

lines = [
    "# Toolkit duty matrix",
    "",
    "<!-- GENERATED by scripts/ci/duty-matrix.sh — do not edit by hand. CI diffs this file",
    "     against a fresh run, so regenerate after changing the Toolkit trait or a backend. -->",
    "",
    "Which backend implements which `Toolkit` duty (`crates/day-spec/src/lib.rs`). `✓` = the",
    "backend defines the method; `·` = it inherits the day-spec default (a no-op or trivial",
    "answer — day-spec documents each). Required duties have no default; every backend must",
    "implement them, and this table proves it.",
    "",
    "| duty | req | " + " | ".join(name for name, _ in backends) + " |",
    "|---|---|" + "---|" * len(backends),
]
for name, required in duties:
    row = [f"`{name}`", "yes" if required else "·"]
    pat = re.compile(r"\bfn " + re.escape(name) + r"\s*(<[^>]*>)?\s*\(\s*&(mut\s+)?self")
    for bname, _ in backends:
        row.append("✓" if pat.search(sources[bname]) else "·")
    lines.append("| " + " | ".join(row) + " |")
lines.append("")

Path("docs/duty-matrix.md").write_text("\n".join(lines))
missing = []
for name, required in duties:
    if not required:
        continue
    pat = re.compile(r"\bfn " + re.escape(name) + r"\s*(<[^>]*>)?\s*\(\s*&(mut\s+)?self")
    for bname, _ in backends:
        if not pat.search(sources[bname]):
            missing.append(f"{bname}: {name}")
if missing:
    raise SystemExit("required duty missing an implementation: " + ", ".join(missing))
print(f"docs/duty-matrix.md: {len(duties)} duties x {len(backends)} backends")
EOF
