#!/usr/bin/env bash
# Copyright © The Daybrite Project
# SPDX-License-Identifier: MPL-2.0
# Regenerate docs/recorder-matrix.md — WHAT THE DAYSCRIPT RECORDER DOES with every `Event` variant
# the app can receive (§14.6). Third of the generated conformance tables, after duty-matrix.sh (the
# Toolkit trait is implemented) and coverage-matrix.sh (the piece vocabulary is rendered); this one
# proves the recorder has a decision about every event, rather than a default of silence.
#
# Why generate it: `event_to_step` ends in a `_ => None` arm, so an event nobody mapped is not a
# compile error, not a test failure, and not visible in review — it is a control that replays
# perfectly and records as nothing. That is exactly how `Button::style(…)` was lost: it is a
# composed `.on_tap` piece, so it delivers `Tap` and never `Pressed`, and only `Pressed` was
# mapped. Deriving the table from the source puts every new `Event` variant in a diff as
# "dropped", where a human has to agree with it.
#
# The runtime half of the same fact is day-script's `playback_and_recording_agree` test, which
# holds the recorder to what the EXECUTOR emits per step. This table covers the other direction:
# the full event vocabulary, mapped or not.
#
#     scripts/ci/recorder-matrix.sh
set -euo pipefail
cd "$(dirname "$0")/../.."

python3 - <<'EOF'
import re
from pathlib import Path

spec = Path("crates/day-spec/src/lib.rs").read_text()
record = Path("crates/day-script/src/record.rs").read_text()


def body_of(src: str, header: re.Pattern) -> str:
    """The brace-balanced body of the first item matching `header`, so a mention in a doc comment
    is never mistaken for a real arm."""
    m = header.search(src)
    if not m:
        return ""
    i = src.index("{", m.end() - 1)
    depth, j = 0, i
    while j < len(src):
        if src[j] == "{":
            depth += 1
        elif src[j] == "}":
            depth -= 1
            if depth == 0:
                return src[i : j + 1]
        j += 1
    return src[i:]


# Every Event variant, in declaration order.
enum_body = body_of(spec, re.compile(r"pub enum Event\b"))
variants = []
for line in enum_body.splitlines():
    line = line.strip()
    if line.startswith("//") or line.startswith("#["):
        continue
    m = re.match(r"([A-Z][A-Za-z0-9]*)\s*(\(|\{|,|$)", line)
    if m:
        variants.append(m.group(1))

# What `event_to_step` maps: each arm's `Event::X` patterns paired with the `Step::Y` it builds.
fn_body = body_of(record, re.compile(r"fn event_to_step\("))
mapped: dict[str, str] = {}
for arm in re.split(r"\n\s{8}(?=Event::|_ =>)", fn_body):
    names = re.findall(r"Event::([A-Z][A-Za-z0-9]*)", arm)
    step = re.search(r"Step::([A-Z][A-Za-z0-9]*)", arm)
    if not names or not step:
        continue
    for n in names:
        mapped[n] = step.group(1)

# The nav observer records route changes instead of `event_to_step` — a real decision, not a gap,
# and the one case where "unmapped here" does not mean "not recorded".
VIA_NAV = {"RouteRequested", "NavBack"}

rows = []
for v in variants:
    if v in mapped:
        rows.append((v, f"`{mapped[v]}`", "recorded"))
    elif v in VIA_NAV:
        rows.append((v, "`Navigate`", "recorded by the nav observer (`on_nav`)"))
    else:
        rows.append((v, "—", "dropped"))

recorded = sum(1 for _, _, d in rows if d.startswith("recorded"))
out = [
    "<!-- Generated by scripts/ci/recorder-matrix.sh — do not edit. -->",
    "",
    "# Dayscript recorder coverage",
    "",
    "Every `Event` a Day app can receive, and the dayscript step the recorder writes for it",
    "(DESIGN.md §14.6). Derived from `day-spec`'s `Event` enum and `day-script`'s `event_to_step`;",
    "CI fails if this file drifts from them.",
    "",
    "**A new `Event` variant lands here as `dropped` by default.** That is the point: the recorder",
    "ends in a catch-all, so an unmapped event is silent at runtime — the control replays but never",
    "records. If a new variant should produce a step, map it in `event_to_step`; if it should not,",
    "the `dropped` row is the record of that decision.",
    "",
    f"{recorded} of {len(rows)} variants record.",
    "",
    "| `Event` | Step | Disposition |",
    "| --- | --- | --- |",
]
out += [f"| `{v}` | {step} | {disp} |" for v, step, disp in rows]
out.append("")

Path("docs/recorder-matrix.md").write_text("\n".join(out))
print(f"docs/recorder-matrix.md: {recorded}/{len(rows)} Event variants recorded")
EOF
