pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
// Generated by `day build` (docs/extending.md); absent before the first build.
val dayPiecesJson: String? = providers
    .fileContents(layout.settingsDirectory.file("../../build/day/android/day-pieces.json"))
    .asText.orNull
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        // Extra Maven repos contributed by standalone pieces (docs/extending.md), staged by
        // `day build` from cargo metadata. Read generically — no per-piece edits here. Read
        // through `providers.fileContents`, so a changed list discards the configuration cache.
        dayPiecesJson?.let { text ->
            @Suppress("UNCHECKED_CAST")
            val pieces = groovy.json.JsonSlurper().parseText(text) as Map<String, Any>
            @Suppress("UNCHECKED_CAST")
            (pieces["repositories"] as? List<String>).orEmpty().forEach { url -> maven { setUrl(url) } }
        }
    }
}
// A constant: Gradle shows it in the IDE and nothing else reads it, so it need not
// carry the package name into a second file (DESIGN.md §17.5 "Renaming a project").
rootProject.name = "dayapp"
include(":app")
